name: .NET Core

on:
  push:
  workflow_dispatch:
  
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test ./RandomQuotes.Tests/RandomQuotes.Tests.csproj --no-build --verbosity normal --logger "trx;LogFileName=xtests.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        trx_files: "*/test_results/xtests.trx"
        
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output './publish'
